DROP TABLE BOA_PROCESS_LOG CASCADE CONSTRAINTS;

CREATE TABLE BOA_PROCESS_LOG
(
  PROCESS      VARCHAR2(1000 BYTE),
  SUB_PROCESS  VARCHAR2(1000 BYTE),
  ENTRYDTE     DATE,
  ROWCOUNTS    NUMBER,
  MESSAGE      VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
