DROP TABLE BOA_FEESRETURN_EXT CASCADE CONSTRAINTS;

CREATE TABLE BOA_FEESRETURN_EXT
(
  TRANSACTION_TYPE  NUMBER(9),
  TRANID            VARCHAR2(50 BYTE),
  TRANKY            VARCHAR2(40 BYTE),
  ERROR_CODE        NUMBER(9),
  ERROR_MESSAGE     VARCHAR2(300 BYTE),
  RESOLVED          NUMBER(1),
  RESEARCHING       NUMBER(1),
  RESENT            NUMBER(1),
  DEV               NUMBER(1),
  BILLED            NUMBER(1)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY LOAD_BOA_FEESRETURN
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED by '\n'
            BADFILE  BOA_LOAD_IPP_LOG: 'BOA_FEESRETURN.bad'
            LOGFILE  BOA_LOAD_IPP_LOG: 'BOA_FEESRETURN.log'
     FIELDS TERMINATED BY '|'
   (
    TRANSACTION_TYPE, TRANID, TRANKY, ERROR_CODE, ERROR_MESSAGE, RESOLVED, RESEARCHING, RESENT, DEV, BILLED
   )
      )
     LOCATION (LOAD_BOA_FEESRETURN:'BOA_FEESRETURN_2072017090058.txt')
  )
REJECT LIMIT UNLIMITED
NOPARALLEL
NOMONITORING;
