DROP TABLE BOA_WORK_ORDER_LIST CASCADE CONSTRAINTS;

CREATE TABLE BOA_WORK_ORDER_LIST
(
  WORK_ORDER  VARCHAR2(60 BYTE)                 NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
