DROP TABLE BOA_PROCESS_LOG_TMP CASCADE CONSTRAINTS;

CREATE TABLE BOA_PROCESS_LOG_TMP
(
  PROCESS      VARCHAR2(1000 BYTE),
  SUB_PROCESS  VARCHAR2(1000 BYTE),
  ENTRYDTE     DATE,
  ROWCOUNTS    NUMBER,
  MESSAGE      VARCHAR2(4000 BYTE),
  PID          NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
