DROP TABLE BOA_FEESRETURN_NONDUPTRAN CASCADE CONSTRAINTS;

CREATE TABLE BOA_FEESRETURN_NONDUPTRAN
(
  TRANSACTION_TYPE  NUMBER(9),
  TRANID            VARCHAR2(50 BYTE),
  WORK_ORDER        VARCHAR2(4000 BYTE),
  DONE_CD           VARCHAR2(4000 BYTE),
  ORDER_DT          VARCHAR2(4000 BYTE),
  TRANKY            VARCHAR2(40 BYTE),
  ERROR_CODE        NUMBER(9),
  ERROR_MESSAGE     VARCHAR2(300 BYTE),
  RESOLVED          NUMBER(1),
  RESEARCHING       NUMBER(1),
  RESENT            NUMBER(1),
  DEV               NUMBER(1),
  BILLED            NUMBER(1),
  RK                NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
