DROP TABLE BOA_FEESRETURNED_ENHANCED CASCADE CONSTRAINTS;

CREATE TABLE BOA_FEESRETURNED_ENHANCED
(
  TRANSACTION_TYPE  NUMBER,
  TRANID            VARCHAR2(100 BYTE),
  WORK_ORDER        VARCHAR2(100 BYTE),
  DONE_CD           VARCHAR2(100 BYTE),
  ORDER_DT          VARCHAR2(30 BYTE),
  TRANKY            VARCHAR2(40 BYTE),
  ERROR_CODE        NUMBER,
  ERROR_MESSAGE     VARCHAR2(300 BYTE),
  RESOLVED          NUMBER(1),
  RESEARCHING       NUMBER(1),
  RESENT            NUMBER(1),
  DEV               NUMBER(1),
  BILLED            NUMBER(1)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
