DROP TABLE BOA_SVC_REL_EXT CASCADE CONSTRAINTS;

CREATE TABLE BOA_SVC_REL_EXT
(
  ACCOUNTID    VARCHAR2(20 BYTE),
  SRLID        VARCHAR2(20 BYTE),
  SRLDATE      VARCHAR2(30 BYTE),
  NEWSERVICER  VARCHAR2(200 BYTE),
  DEREGISTER   VARCHAR2(10 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY BOA_SVC_REL_DIR
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED by Newline
            BADFILE  LOAD_SGP_FEES: 'BOA_SVC_REL_EXT.bad'
            LOGFILE  LOAD_SGP_FEES: 'BOA_SVC_REL_EXT.log'
             FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"' 
          (
      ACCOUNTID,  
      SRLID,
      SRLDate,
      NewServicer,
      Deregister
      )
    )
     LOCATION (BOA_SVC_REL_DIR:'20160602_Safeguard_TransmitT1_T15.xlsx.csv')
  )
REJECT LIMIT UNLIMITED
NOPARALLEL
NOMONITORING;
