DROP TABLE BOA_FEE_STATUS_LOG CASCADE CONSTRAINTS;

CREATE TABLE BOA_FEE_STATUS_LOG
(
  PROCESS      VARCHAR2(100 BYTE),
  PER_COMPETE  NUMBER(10,2),
  ENTRY_DATE   DATE,
  PID          NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
