DROP TABLE BOA_BILLING_LOAD_QUEUE CASCADE CONSTRAINTS;

CREATE TABLE BOA_BILLING_LOAD_QUEUE
(
  PID           NUMBER(10),
  CLIENT        VARCHAR2(100 BYTE),
  FILE_NAME     VARCHAR2(200 BYTE),
  COMPLETED     NUMBER(2)                       DEFAULT 0,
  ENTRYDTE      DATE,
  LOAD_COMPLTE  VARCHAR2(5 BYTE)                DEFAULT 'NO',
  FILE_TYPE     VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX BOA_BILLING_LOAD_QUEUE_PID ON BOA_BILLING_LOAD_QUEUE
(PID)
LOGGING
NOPARALLEL;
