DROP TABLE BOA_NAV_ARINVOICING CASCADE CONSTRAINTS;

CREATE TABLE BOA_NAV_ARINVOICING
(
  RECORD_TYPE      VARCHAR2(1 BYTE),
  INVOICE_DATE     VARCHAR2(20 BYTE),
  INVOICE_NBR      VARCHAR2(30 BYTE),
  ORDER_NBR        VARCHAR2(30 BYTE),
  BILL_CODE        VARCHAR2(20 BYTE),
  CLIENT_CODE      VARCHAR2(20 BYTE),
  BILL_TO_CODE     VARCHAR2(20 BYTE),
  DEPT             VARCHAR2(20 BYTE),
  X1               VARCHAR2(20 BYTE),
  PROP_NBR         VARCHAR2(20 BYTE),
  LOAN_NBR         VARCHAR2(20 BYTE),
  VENDOR_CODE      VARCHAR2(20 BYTE),
  WORK_CODE        VARCHAR2(20 BYTE),
  X2               VARCHAR2(20 BYTE),
  X3               VARCHAR2(20 BYTE),
  CONS             VARCHAR2(20 BYTE),
  SALES            NUMBER,
  COSTS            NUMBER,
  X4               VARCHAR2(20 BYTE),
  X5               VARCHAR2(20 BYTE),
  PHOTOS           VARCHAR2(20 BYTE),
  X6               VARCHAR2(20 BYTE),
  X7               VARCHAR2(20 BYTE),
  ORDER_DATE       VARCHAR2(20 BYTE),
  STATE            VARCHAR2(100 BYTE),
  ZIP              VARCHAR2(20 BYTE),
  CONTROL_NBR      VARCHAR2(100 BYTE),
  ORDER_BY_NAME    VARCHAR2(100 BYTE),
  COMPLETION_DATE  VARCHAR2(20 BYTE),
  OCCUPANCY        VARCHAR2(5 BYTE),
  LOAN_TYPE        VARCHAR2(20 BYTE),
  ZIP_CODE2        VARCHAR2(20 BYTE),
  TAX_AMOUNT       NUMBER,
  EXEMPT_AMOUNT    NUMBER,
  EXEMPT_REASON    VARCHAR2(100 BYTE),
  TAX_PERCENT      NUMBER,
  PID              NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
