DROP TABLE BOA_SUMMARY_GOOD_DEDUP CASCADE CONSTRAINTS;

CREATE TABLE BOA_SUMMARY_GOOD_DEDUP
(
  TRANSACTION    NUMBER,
  TRANID         VARCHAR2(100 BYTE),
  WORK_ORDER     VARCHAR2(30 BYTE),
  DONE_CD        VARCHAR2(30 BYTE),
  ORDER_DT       VARCHAR2(30 BYTE),
  TRANKY         VARCHAR2(40 BYTE),
  ERROR_CODE     NUMBER,
  ERROR_MESSAGE  VARCHAR2(300 BYTE),
  RESOLVED       NUMBER,
  RESEARCHING    NUMBER,
  RESENT         NUMBER,
  DEV            NUMBER,
  BILLED         NUMBER,
  SOURCE         VARCHAR2(100 BYTE),
  LOAN           NUMBER,
  TRAN_DT        VARCHAR2(10 BYTE),
  TRANCODE       VARCHAR2(10 BYTE),
  PRICE          NUMBER,
  WT             VARCHAR2(10 BYTE),
  SWT            VARCHAR2(10 BYTE),
  PRICEPER       NUMBER,
  QTY            NUMBER,
  UOM            VARCHAR2(10 BYTE),
  SERVICEID      NUMBER,
  ZIP            VARCHAR2(10 BYTE),
  STATE          VARCHAR2(3 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
