DROP TABLE BOA_SUMMARY CASCADE CONSTRAINTS;

CREATE TABLE BOA_SUMMARY
(
  TRANSACTION    NUMBER(9),
  TRANID         VARCHAR2(100 BYTE),
  WORK_ORDER     VARCHAR2(30 BYTE),
  DONE_CD        VARCHAR2(30 BYTE),
  ORDER_DT       VARCHAR2(30 BYTE),
  TRANKY         VARCHAR2(40 BYTE),
  ERROR_CODE     NUMBER(9),
  ERROR_MESSAGE  VARCHAR2(300 BYTE),
  RESOLVED       NUMBER(1),
  RESEARCHING    NUMBER(1),
  RESENT         NUMBER(1),
  DEV            NUMBER(1),
  BILLED         NUMBER(1),
  SOURCE         VARCHAR2(100 BYTE),
  LOAN           NUMBER(9),
  TRAN_DT        VARCHAR2(10 BYTE),
  TRANCODE       VARCHAR2(10 BYTE),
  PRICE          NUMBER(9),
  WT             VARCHAR2(10 BYTE),
  SWT            VARCHAR2(10 BYTE),
  PRICEPER       NUMBER(9),
  QTY            NUMBER(9),
  UOM            VARCHAR2(10 BYTE),
  SERVICEID      NUMBER(9),
  ZIP            VARCHAR2(10 BYTE),
  STATE          VARCHAR2(2 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
PARALLEL ( DEGREE 4 INSTANCES 1 )
MONITORING;


CREATE INDEX SUMMARY_ORDER_DT_IDX ON BOA_SUMMARY
(ORDER_DT)
LOGGING
NOPARALLEL;


CREATE INDEX SUMMARY_WORKORDER_IDX ON BOA_SUMMARY
(WORK_ORDER)
LOGGING
NOPARALLEL;
