DROP TABLE BOFA_FILES_PROCESSED CASCADE CONSTRAINTS;

CREATE TABLE BOFA_FILES_PROCESSED
(
  PID         NUMBER(9),
  CLIENT      VARCHAR2(100 BYTE),
  FILE_NAME   VARCHAR2(1000 BYTE),
  RECORDCNT   NUMBER,
  ENTRY_DATE  DATE,
  COMMENTS    VARCHAR2(1000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
