DROP TABLE CRITERIA_MIA CASCADE CONSTRAINTS;

CREATE TABLE CRITERIA_MIA
(
  WORK_ORDER  VARCHAR2(4000 BYTE),
  TRANKY      VARCHAR2(120 BYTE),
  ENTRYDT     DATE,
  CREATED_BY  VARCHAR2(120 BYTE),
  PID         NUMBER,
  PKEY        NUMBER                            NOT NULL,
  CATEGORY    VARCHAR2(600 BYTE),
  COMMENTS    VARCHAR2(900 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
