DROP TABLE FILE_ERRORS_EXT CASCADE CONSTRAINTS;

CREATE TABLE FILE_ERRORS_EXT
(
  MESSAGE  VARCHAR2(4000 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY FILE_ERROR_DIR
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED BY NEWLINE
       NOBADFILE
       NODISCARDFILE
       NOLOGFILE
       SKIP 0
       FIELDS TERMINATED BY '\n'
       OPTIONALLY ENCLOSED BY '"' AND '"'
       MISSING FIELD VALUES ARE NULL
       REJECT ROWS WITH ALL NULL FIELDS
       (
         MESSAGE Char
       )     )
     LOCATION (FILE_ERROR_DIR:'DuplicateOrderCheckSGP_SWEEP_09-08-15.csv.err')
  )
REJECT LIMIT UNLIMITED
NOPARALLEL
NOMONITORING;
