DROP TABLE LA_OUTSTANDING_ADJUSTED_EXT CASCADE CONSTRAINTS;

CREATE TABLE LA_OUTSTANDING_ADJUSTED_EXT
(
  INVOICE_NBR      VARCHAR2(200 BYTE),
  VENDOR           VARCHAR2(200 BYTE),
  VENDOR_CONTACT   VARCHAR2(200 BYTE),
  LOAN_NBR         VARCHAR2(100 BYTE),
  INVOICE_DATE     VARCHAR2(30 BYTE),
  DEPT             VARCHAR2(10 BYTE),
  STATE            VARCHAR2(10 BYTE),
  BORROWER         VARCHAR2(100 BYTE),
  ADJUSTED_TOTAL   VARCHAR2(30 BYTE),
  EARLIEST_ADJ_DT  VARCHAR2(30 BYTE),
  CURTAIL_DATE     VARCHAR2(30 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY SGP_LA_FILES
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED by Newline
          LOGFILE SGP_LA_FILES:'OutStndAdj.log'
                BADFILE SGP_LA_FILES:'OutStndAdj.bad'
                DISCARDFILE SGP_LA_FILES:'OutStndAdj.disc'
           FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'   
          (INVOICE_NBR,
           VENDOR,
           VENDOR_CONTACT,
           LOAN_NBR,
           INVOICE_DATE,
           DEPT,
           STATE,
           BORROWER,
          ADJUSTED_TOTAL,
          EARLIEST_ADJ_DT,
          CURTAIL_DATE)
     )
     LOCATION (SGP_LA_FILES:'OutAdj_20170214.xls.xlsx.csv')
  )
REJECT LIMIT UNLIMITED
NOPARALLEL
NOMONITORING;
