DROP TABLE LA_OUTSTANDING_ADJUSTED_EXT CASCADE CONSTRAINTS;

CREATE TABLE LA_OUTSTANDING_ADJUSTED_EXT
(
  CLIENT           VARCHAR2(100 BYTE),
  INVOICE_NBR      VARCHAR2(200 BYTE),
  VENDOR           VARCHAR2(200 BYTE),
  VENDOR_CONTACT   VARCHAR2(200 BYTE),
  WORKORDER_NBR    VARCHAR2(30 BYTE),
  LOAN_NBR         VARCHAR2(100 BYTE),
  INVOICE_DATE     VARCHAR2(20 BYTE),
  DEPT             VARCHAR2(10 BYTE),
  STATE            VARCHAR2(10 BYTE),
  BORROWER         VARCHAR2(100 BYTE),
  INVOICE_AMT      VARCHAR2(30 BYTE),
  DISPUTE_AMT      VARCHAR2(30 BYTE),
  ADJUSTED_TOTAL   VARCHAR2(30 BYTE),
  EARLIEST_ADJ_DT  VARCHAR2(20 BYTE),
  CURTAIL_DATE     VARCHAR2(20 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY SGP_LA_FILES
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED by Newline
           NOBADFILE
           NODISCARDFILE
           NOLOGFILE
           FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'   
          (CLIENT,
          INVOICE_NBR,
          VENDOR,
          VENDOR_CONTACT,
          WORKORDER_NBR,
          LOAN_NBR,
          INVOICE_DATE,
          DEPT,
          STATE,
          BORROWER,
          INVOICE_AMT,
          DISPUTE_AMT,
          ADJUSTED_TOTAL,
          EARLIEST_ADJ_DT,
          CURTAIL_DATE)
     )
     LOCATION (SGP_LA_FILES:'OutAdj_20160722.csv')
  )
REJECT LIMIT UNLIMITED
NOPARALLEL
NOMONITORING;
