ALTER TABLE LA_PENDING_APPROVAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE LA_PENDING_APPROVAL CASCADE CONSTRAINTS;

CREATE TABLE LA_PENDING_APPROVAL
(
  SERVICER         VARCHAR2(200 BYTE),
  LOAN_NBR         VARCHAR2(30 BYTE),
  INVOICE_TYPE     VARCHAR2(100 BYTE),
  INVOICE_DATE     VARCHAR2(30 BYTE),
  INVOICE_NBR      VARCHAR2(30 BYTE),
  STATE            VARCHAR2(100 BYTE),
  LI_CODE          VARCHAR2(200 BYTE),
  LI_DESCRIPTION   VARCHAR2(4000 BYTE),
  LI_AMT           VARCHAR2(30 BYTE),
  ADJUSTED_AMT     VARCHAR2(30 BYTE),
  TOTAL_LI_AMOUNT  VARCHAR2(30 BYTE),
  REASON           VARCHAR2(4000 BYTE),
  COMMENTS_DATE    VARCHAR2(30 BYTE),
  EXPIRES_IN       VARCHAR2(10 BYTE),
  LOAD_ID          NUMBER,
  FILE_ID          NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index IPP$LIBRARIAN.SYS_C006998.
--  The object is created when the parent object is created.

ALTER TABLE LA_PENDING_APPROVAL ADD (
  PRIMARY KEY
  (LOAD_ID)
  ENABLE VALIDATE);
