DROP TABLE POLS_ADDRS CASCADE CONSTRAINTS;

CREATE TABLE POLS_ADDRS
(
  LOANNUMBER       VARCHAR2(40 BYTE),
  SPICLIENT        VARCHAR2(40 BYTE),
  SPIPROPID        VARCHAR2(40 BYTE),
  ADDRESS_LINE1    VARCHAR2(40 BYTE),
  ADDRESS_LINE2    VARCHAR2(40 BYTE),
  CITY             VARCHAR2(40 BYTE),
  STATE            VARCHAR2(40 BYTE),
  ZIPCODE          VARCHAR2(20 BYTE),
  COUNTY           VARCHAR2(40 BYTE),
  PROP_IND         VARCHAR2(50 BYTE),
  PROPERTYLOTSIZE  VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
