DROP TABLE REBILL_TEST CASCADE CONSTRAINTS;

CREATE TABLE REBILL_TEST
(
  CLIENTID     VARCHAR2(20 BYTE),
  WORK_ORDER   VARCHAR2(40 BYTE),
  INVOICE_NBR  VARCHAR2(40 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
