DROP TABLE RETURN_LIST CASCADE CONSTRAINTS;

CREATE TABLE RETURN_LIST
(
  CAL_DATE      VARCHAR2(12 BYTE),
  TIMES         VARCHAR2(10 BYTE),
  FILENAME_DTE  VARCHAR2(30 BYTE),
  FILENAME      VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
