DROP TABLE SCHEMA_VARIABLES CASCADE CONSTRAINTS;

CREATE TABLE SCHEMA_VARIABLES
(
  PID        NUMBER,
  VAR_NAME   VARCHAR2(4000 BYTE),
  VAR_VALUE  VARCHAR2(4000 BYTE),
  COMMENTS   VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
