DROP TABLE SGP_FEES CASCADE CONSTRAINTS;

CREATE TABLE SGP_FEES
(
  TRANID     VARCHAR2(100 BYTE),
  LOAN       NUMBER(10),
  SENTDATE   VARCHAR2(30 BYTE),
  TRANCODE   VARCHAR2(20 BYTE),
  PRICE      NUMBER,
  FIELD6     VARCHAR2(100 BYTE),
  FIELD7     NUMBER,
  FIELD8     VARCHAR2(100 BYTE),
  FIELD9     VARCHAR2(100 BYTE),
  FIELD10    NUMBER,
  FIELD11    VARCHAR2(100 BYTE),
  WT         NUMBER,
  SWT        NUMBER,
  PRICEPER   NUMBER,
  QTY        NUMBER,
  UOM        VARCHAR2(10 BYTE),
  SERVICEID  NUMBER,
  ZIP        VARCHAR2(10 BYTE),
  PID        NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SGP_FEES_PID ON SGP_FEES
(PID)
LOGGING
NOPARALLEL;


CREATE INDEX SGP_FEES_TRANID_IDX ON SGP_FEES
(TRANID)
NOLOGGING
NOPARALLEL;
