DROP TABLE SGP_FEESRETURN_PROCESSED_PIDS CASCADE CONSTRAINTS;

CREATE TABLE SGP_FEESRETURN_PROCESSED_PIDS
(
  PID  NUMBER(10),
  CNT  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SGP_FEESRETURN_PROCESSED_PID ON SGP_FEESRETURN_PROCESSED_PIDS
(PID)
LOGGING
NOPARALLEL;
