DROP TABLE SGP_PPOINVOICING_ENHANCED CASCADE CONSTRAINTS;

CREATE TABLE SGP_PPOINVOICING_ENHANCED
(
  TRANID      VARCHAR2(100 BYTE),
  WORK_ORDER  VARCHAR2(40 BYTE),
  DONE_CD     VARCHAR2(40 BYTE),
  ORDER_DT    VARCHAR2(40 BYTE),
  LOAN        VARCHAR2(40 BYTE),
  SENTDATE    VARCHAR2(30 BYTE),
  TRANCODE    VARCHAR2(100 BYTE),
  PRICE       VARCHAR2(100 BYTE),
  FIELD6      VARCHAR2(100 BYTE),
  FIELD7      VARCHAR2(100 BYTE),
  FIELD8      VARCHAR2(100 BYTE),
  FIELD9      VARCHAR2(100 BYTE),
  FIELD10     VARCHAR2(100 BYTE),
  FIELD11     VARCHAR2(100 BYTE),
  WT          VARCHAR2(10 BYTE),
  SWT         VARCHAR2(10 BYTE),
  PRICEPER    VARCHAR2(100 BYTE),
  QTY         VARCHAR2(10 BYTE),
  UOM         VARCHAR2(10 BYTE),
  SERVICEID   VARCHAR2(10 BYTE),
  ZIP         VARCHAR2(10 BYTE),
  PID         NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SGP_PPO_ENHANCED_PID ON SGP_PPOINVOICING_ENHANCED
(PID)
LOGGING
NOPARALLEL;
