DROP TABLE SGP_PPOINVOICING CASCADE CONSTRAINTS;

CREATE TABLE SGP_PPOINVOICING
(
  TRANID     VARCHAR2(100 BYTE),
  LOAN       VARCHAR2(40 BYTE),
  SENTDATE   VARCHAR2(30 BYTE),
  TRANCODE   VARCHAR2(100 BYTE),
  PRICE      VARCHAR2(100 BYTE),
  FIELD6     VARCHAR2(100 BYTE),
  FIELD7     VARCHAR2(100 BYTE),
  FIELD8     VARCHAR2(100 BYTE),
  FIELD9     VARCHAR2(100 BYTE),
  FIELD10    VARCHAR2(100 BYTE),
  FIELD11    VARCHAR2(100 BYTE),
  WT         VARCHAR2(10 BYTE),
  SWT        VARCHAR2(10 BYTE),
  PRICEPER   VARCHAR2(100 BYTE),
  QTY        VARCHAR2(10 BYTE),
  UOM        VARCHAR2(10 BYTE),
  SERVICEID  VARCHAR2(10 BYTE),
  ZIP        VARCHAR2(10 BYTE),
  PID        NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
