DROP TABLE VARIANCE_WORKORDERS CASCADE CONSTRAINTS;

CREATE TABLE VARIANCE_WORKORDERS
(
  WORK_ORDER  VARCHAR2(20 BYTE),
  PUNCH_CODE  VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
