DROP TABLE XCL_SWEEP CASCADE CONSTRAINTS;

CREATE TABLE XCL_SWEEP
(
  CLIENT_NAME  VARCHAR2(40 BYTE),
  SHEETNAME    VARCHAR2(40 BYTE),
  ACCT         VARCHAR2(40 BYTE),
  CURRENT_     VARCHAR2(40 BYTE),
  CURRENTDTL   VARCHAR2(40 BYTE),
  RECACTION    VARCHAR2(40 BYTE),
  LOAD_DT      DATE,
  PID          NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
