DROP TABLE XCL_CHL_SWEEP_EXT CASCADE CONSTRAINTS;

CREATE TABLE XCL_CHL_SWEEP_EXT
(
  SHEETNAME   VARCHAR2(40 BYTE),
  ACCT        VARCHAR2(40 BYTE),
  CURRENT_    VARCHAR2(40 BYTE),
  CURRENTDTL  VARCHAR2(40 BYTE),
  RECACTION   VARCHAR2(40 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY XCL_CHL_SWEEP_DIR
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED BY NEWLINE
       NOBADFILE
       NODISCARDFILE
       NOLOGFILE
       SKIP 0
       FIELDS TERMINATED BY ','
       MISSING FIELD VALUES ARE NULL
       REJECT ROWS WITH ALL NULL FIELDS
       (
         SheetName Char,
         acct Char,
         Current_ Char,
         CurrentDtl Char,
         RecAction Char
       )      )
     LOCATION (XCL_CHL_SWEEP_DIR:'DuplicateOrderCheckSGP_SWEEP_02-07-17-123636825.csv.out')
  )
REJECT LIMIT UNLIMITED
NOPARALLEL
NOMONITORING;
